[package]
name = "songforobs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
mpris = "2.0.1"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
